// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNumber    int32                  `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *PageInfo) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserCount     int32                  `protobuf:"varint,1,opt,name=userCount,proto3" json:"userCount,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *UserList) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MobileNumber  string                 `protobuf:"bytes,2,opt,name=mobileNumber,proto3" json:"mobileNumber,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Role          int32                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetMobileNumber() string {
	if x != nil {
		return x.MobileNumber
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type PasswordVerify struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RawPassword     string                 `protobuf:"bytes,1,opt,name=rawPassword,proto3" json:"rawPassword,omitempty"`
	EncodedPassword string                 `protobuf:"bytes,2,opt,name=encodedPassword,proto3" json:"encodedPassword,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PasswordVerify) Reset() {
	*x = PasswordVerify{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordVerify) ProtoMessage() {}

func (x *PasswordVerify) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordVerify.ProtoReflect.Descriptor instead.
func (*PasswordVerify) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordVerify) GetRawPassword() string {
	if x != nil {
		return x.RawPassword
	}
	return ""
}

func (x *PasswordVerify) GetEncodedPassword() string {
	if x != nil {
		return x.EncodedPassword
	}
	return ""
}

type PasswordVerifyPass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPass        bool                   `protobuf:"varint,1,opt,name=isPass,proto3" json:"isPass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordVerifyPass) Reset() {
	*x = PasswordVerifyPass{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordVerifyPass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordVerifyPass) ProtoMessage() {}

func (x *PasswordVerifyPass) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordVerifyPass.ProtoReflect.Descriptor instead.
func (*PasswordVerifyPass) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *PasswordVerifyPass) GetIsPass() bool {
	if x != nil {
		return x.IsPass
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"F\n" +
	"\bPageInfo\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x01 \x01(\x05R\n" +
	"pageNumber\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"I\n" +
	"\bUserList\x12\x1c\n" +
	"\tuserCount\x18\x01 \x01(\x05R\tuserCount\x12\x1f\n" +
	"\x05users\x18\x02 \x03(\v2\t.UserInfoR\x05users\"\xa2\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\fmobileNumber\x18\x02 \x01(\tR\fmobileNumber\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\"\\\n" +
	"\x0ePasswordVerify\x12 \n" +
	"\vrawPassword\x18\x01 \x01(\tR\vrawPassword\x12(\n" +
	"\x0fencodedPassword\x18\x02 \x01(\tR\x0fencodedPassword\",\n" +
	"\x12PasswordVerifyPass\x12\x16\n" +
	"\x06isPass\x18\x01 \x01(\bR\x06isPass2\xcc\x01\n" +
	"\x04User\x12#\n" +
	"\vGetUserList\x12\t.PageInfo\x1a\t.UserList\x12\x1f\n" +
	"\aGetUser\x12\t.UserInfo\x1a\t.UserInfo\x12\"\n" +
	"\n" +
	"CreateUser\x12\t.UserInfo\x1a\t.UserInfo\x12\"\n" +
	"\n" +
	"UpdateUser\x12\t.UserInfo\x1a\t.UserInfo\x126\n" +
	"\x0eVerifyPassword\x12\x0f.PasswordVerify\x1a\x13.PasswordVerifyPassB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*PageInfo)(nil),           // 0: PageInfo
	(*UserList)(nil),           // 1: UserList
	(*UserInfo)(nil),           // 2: UserInfo
	(*PasswordVerify)(nil),     // 3: PasswordVerify
	(*PasswordVerifyPass)(nil), // 4: PasswordVerifyPass
}
var file_user_proto_depIdxs = []int32{
	2, // 0: UserList.users:type_name -> UserInfo
	0, // 1: User.GetUserList:input_type -> PageInfo
	2, // 2: User.GetUser:input_type -> UserInfo
	2, // 3: User.CreateUser:input_type -> UserInfo
	2, // 4: User.UpdateUser:input_type -> UserInfo
	3, // 5: User.VerifyPassword:input_type -> PasswordVerify
	1, // 6: User.GetUserList:output_type -> UserList
	2, // 7: User.GetUser:output_type -> UserInfo
	2, // 8: User.CreateUser:output_type -> UserInfo
	2, // 9: User.UpdateUser:output_type -> UserInfo
	4, // 10: User.VerifyPassword:output_type -> PasswordVerifyPass
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
